### ISSUE TITLE
How hard is it to reimplement the emacs primitives in any language 

### ISSUE THREAD

**Issue by Immortalin** [hraberg/deuce#24]
Hey there, I am interested in reimplementing the emacs primitives in Nim/Go and I am curious about how it is to do so e.g.  How many hours are needed. (I am currently using your repository as a reference as clojure is way more readable than C) I don't plan to replace elisp or anything (for the elisp part I am just going to embed guile). I don't mean a full blown exact emacs replica, just enough to get a GUI and things working I.e useable for day to day use. The reason I am doing this because of curiosity and also because emac's concurrency issues are driving me nuts.

**Comment by hraberg** [comment]
If I know what I do today when I started this project I would probably given up before writing any code :-)

It's hard because Emacs is a monolith that hangs pretty much together. Any time you try to by-pass or not aim for compatibility, there's a risk to introduce issues which may trigger bugs in unexpected places. You'll end up spending lot of time debugging Emacs Lisp (of which there's an vast amount) you haven't written or understand calling your code and trying to figure out what's going wrong. Often its hard to isolate things and get them to work by by one.

Having said that, it's probably not impossible. I've spent maybe 4 months on Deuce in total. But Deuce is far from working for real. I intend to keep pushing Deuce a bit further, but if I would start again I would consider writing an Emacs-like editor instead of porting Emacs. Backwards compatibility complicates interesting changes like a new concurrency model for example.

Embedding Guile's Emacs Lisp implementation in another language than C is an interesting approach. (If one likes Scheme, I guess Guile Scheme could be that language.) Do you have a repo for your project?

**Comment by Immortalin** [comment]
Sorry but I don't have a repo yet. I am probably going to use GtKtextBuffer for the buffer implementation(as they have a nice rope data structure implementation out of the box, may be swapped out in future for a more native implementation), Gtk for GUI(it's really easy to build a source code editor due to the source view component, will be swapped out for Libui in future when it becomes more mature). I chose Guile mainly because ease of embedding and nothing else(I am rather indifferent towards scheme), using nim for the editor makes things much easier as I can easily import in C code via its great FFI or just convert them to him with C2Nim. I will probably use it for implementing some of the primitives(since according to your README there are more than 1000 primitives).

**Comment by hraberg** [comment]
Looking forward to see your progress. I haven't looked at Guile Emacs for quite some time, but seem to recall that it kind of works these days.

When porting Emacs, while the primitives are well documented, and the C code quite easy to read, there are also other core parts of the C code that glues everything together that one needs to read and figure out how real to keep. I'm thinking about the command loop and rendering etc.

Nim looks really interesting / nice, but have never written any myself. Do you plan to reuse parts of the C version of Emacs? That was one of the other approaches I considered early on, to basically chip away and convert it piece by piece. This is potentially more viable in Nim than a JVM-based language.

**Comment by Ericson2314** [comment]
@Immortalin If you really want to be a hero, I'd finish BT Templeton GSOC's work with https://www.emacswiki.org/emacs/GuileEmacs , and then with your new-found fame among emacs users spearhead a project replacing the C bits with something better a la neovim.

If guile's elisp doesn't yet work with emacs's C, I'd be skeptical one would get farther *simultaneously* swapping out the C bits and the legacy elisp implementation.

**Comment by Immortalin** [comment]
@Ericson2314 I will think about it :D

**Comment by Immortalin** [comment]
@hraberg https://news.ycombinator.com/item?id=13884322
